kafka:
  bootstrap-servers: localhost:9092
  value-serializer: ru.practicum.serializer.AvroSerializer
  value-deserializer: ru.practicum.deserializer.SensorEventAvroDeserializer
  consumer:
    group-id: aggregator-group